export const TIPOS_TOKEN = {
    "RESERVADO" : "RERSERVADO",
    "DELIMITADOR" : "DELIMITADOR",
    "CADENA" : "CADENA_TEXTO",
    "NUMERO" : "NUMERO",
    "IDENTIFICADOR" : "IDENTIFICADOR",
    "OPERADOR_SUMA" : "OPERADOR_SUMA",
    "OPERADOR_RESTA" : "OPERADOR_RESTA",
    "OPERADOR_MULT" : "OPERADOR_MULTIPLICACION",
    "OPERADOR_ASIGNACION" : "OPERADOR_ASIGNACION",
    "OPERADOR_RACIONAL" : "OPERADOR_RACIONAL",
    "OPERADOR_LOGICO" : "OPERADOR_LOGICO",
    "OPERADOR_DIV" : "OPERADOR_DIVISION",
    "COMENTARIO_LINEA" : "COMENTARIO_LINEA",
    "APERTURA_BLOQUE" : "APERTURA_BLOQUE",
    "CERRADURA_BLOQUE" : "CERRADURA_BLOQUE"
}